[bindings.kotlin]
package_name = "ai.edgefirst.client"
cdylib_name = "edgefirst_client"
generate_immutable_records = true
android = true

[bindings.swift]
module_name = "EdgeFirstClient"
ffi_module_name = "EdgeFirstClientFFI"
cdylib_name = "edgefirst_client"
generate_immutable_records = true
